import mongoose from 'mongoose';

const dailyWordSchema = new mongoose.Schema({
    word: {
        type: String,
        required: true,
        minlength: 5,
        maxlength: 5,
        uppercase: true
    },
    date: {
        type: Date,
        required: true,
        unique: true
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        default: null // Null for auto-generated words
    },
    hint: {
        type: String,
        default: ''
    },
    isAutoGenerated: {
        type: Boolean,
        default: true
    }
}, {
    timestamps: true
});

// Index for efficient date queries
dailyWordSchema.index({ date: 1 });

export default mongoose.model('DailyWord', dailyWordSchema);
